# Generated by Django 4.2 on 2023-05-02 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('phonenumber', models.CharField(max_length=255)),
                ('age', models.CharField(max_length=255)),
                ('blood_group', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('volume_of_blood_donated', models.CharField(max_length=255)),
            ],
        ),
    ]
